"""Shared schemas. These are the contracts between every stage of the pipeline."""

from .common import (
    Size3,
    Vec2,
    Vec3,
    point_in_polygon,
    polygon_area,
    polygon_bounds,
    polygon_centroid,
)
from .floorplan import (
    DimensionTick,
    FloorPlan,
    FloorPlanExtraction,
    Opening,
    OpeningExtraction,
    OpeningType,
    Room,
    RoomExtraction,
    RoomType,
    ScaleCalibration,
    SwingDirection,
    Wall,
    WallExtraction,
)
from .product import (
    BillOfMaterials,
    BOMLine,
    DesignStyle,
    Dimensions,
    Product,
    ProductCategory,
    ProductMatch,
    ProductQuery,
)
from .render import (
    ConditioningMaps,
    ConsistencyScores,
    DesignJob,
    DesignRequest,
    DesignVariation,
    JobStatus,
    RegenerateRequest,
    Render,
    RenderStatus,
)
from .scene import (
    Camera,
    ColorPalette,
    LightSource,
    ObjectRole,
    PlacedObject,
    RoomFinishes,
    Scene,
    SurfaceFinish,
)

__all__ = [
    # common
    "Vec2",
    "Vec3",
    "Size3",
    "polygon_area",
    "polygon_centroid",
    "polygon_bounds",
    "point_in_polygon",
    # floorplan
    "FloorPlan",
    "FloorPlanExtraction",
    "Room",
    "RoomExtraction",
    "RoomType",
    "Wall",
    "WallExtraction",
    "Opening",
    "OpeningExtraction",
    "OpeningType",
    "SwingDirection",
    "ScaleCalibration",
    "DimensionTick",
    # product
    "Product",
    "ProductCategory",
    "ProductQuery",
    "ProductMatch",
    "Dimensions",
    "DesignStyle",
    "BillOfMaterials",
    "BOMLine",
    # scene
    "Scene",
    "PlacedObject",
    "ObjectRole",
    "Camera",
    "ColorPalette",
    "LightSource",
    "RoomFinishes",
    "SurfaceFinish",
    # render
    "Render",
    "RenderStatus",
    "ConditioningMaps",
    "ConsistencyScores",
    "DesignJob",
    "DesignRequest",
    "DesignVariation",
    "JobStatus",
    "RegenerateRequest",
]
